# spec:
#     - test/end-to-end/**/*.test.js
slow: 20000
timeout: 40000
exit: true
require:
    - "@babel/register"
    - test/test.mocha.env
reporter: mocha-multi-reporters
reporter-option:
    - configFile=mocha-multi-reporters.json
