spec:
    - test/end-to-end/**/*.test.js
slow: 20000
timeout: 30000
exit: true
reporter: mochawesome
reporter-option:
    - "reportDir=test_report/mochawesome"
require:
    - "@babel/register"
    - test/test.mocha.env
