name: "Chromatic"

on:
    push:
        branches: [master, "[0-9]*.[0-9]*"]
    workflow_dispatch:

jobs:
    chromatic:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: npm ci

            - name: Publish to Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
