name: "Pre commit hook check"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-title:
        name: Pre commit hook check
        runs-on: ubuntu-latest
        container: rishabhpoddar/supertokens_website_sdk_testing
        steps:
            - uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: git init && git add --all && git -c user.name='test' -c user.email='test@example.com' commit -m 'init for pr action'
            - run: npm i --force || true
            # the below command is there cause otherwise running npm run check-circular-dependencies gives an error like:
            #   Your cache folder contains root-owned files, due to a bug in
            #   npm ERR! previous versions of npm which has since been addressed.
            - run: chown -R 1001:121 "/github/home/.npm"
            - run: npm i --force
            - run: cd test/with-typescript && npm i --force
            - run: ./hooks/pre-commit.sh
