name: "Run visual tests"
on: workflow_dispatch
jobs:
    test_job:
        name: Run visual tests
        timeout-minutes: 120
        runs-on: ubuntu-latest
        container:
            image: rishabhpoddar/supertokens_website_sdk_testing_node_16
            options: "-u 1001"
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Make git use https instead of ssh
              run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
            - run: npm run init
            - name: Cloning supertokens-root
              run: cd ../ && git clone https://github.com/supertokens/supertokens-root.git
            - name: Modifying modules.txt in supertokens-root
              run: cd ../supertokens-root && echo "core,master,supertokens\nplugin-interface,master,supertokens" > modules.txt
            - name: Contents of modules.txt
              run: cat ../supertokens-root/modules.txt
            - name: Running loadModules in supertokens-root
              run: cd ../supertokens-root && ./loadModules
            - name: Installing supertokens-node
              run: cd test/server/ && npm i -d --force && npm i --force github:supertokens/supertokens-node
            - name: Setting up supertokens-root test environment
              run: cd ../supertokens-root && bash ./utils/setupTestEnv --local
            - name: Run tests
              run: npm run test-visual
